ExpiryTracker. Implement delete images from local and remote sources
- Fix crash in Edit caused by adding image downloaded from Google Photos
^ Error: FATAL EXCEPTION: main
         Process: com.zn.expirytracker.free.debug, PID: 21938
         java.lang.RuntimeException: Failure delivering result to activity
         Caused by: java.lang.NullPointerException
             at java.io.File.<init>(File.java:283)
             at com.zn.expirytracker.ui.EditFragment.addImageFromUri(EditFragment.java:1306)

- Remove locally cached images added in Add/Edit after dismissing/saving

Signed-off-by: Teddy Rodriguez <cia.123trod@gmail.com>